--liquibase formatted sql
--changeset ${vr_owner_user}_CODE:VIEW_SDATA_AUDIT_VIEW runOnChange:TRUE  failOnError:TRUE splitStatements:TRUE


  CREATE OR REPLACE FORCE VIEW "SDATA_AUDIT_VIEW" ("WIDGET_ID", "ACTION_TYPE", "EMAIL_ID", "CREATED_ON", "AUDIT_KEY", "AUDIT_VALUE", "MODIFIED_FROM_VALUE") AS 
  SELECT a.WIDGET_ID,
          a.ACTION_TYPE,
          a.EMAIL_ID,
          a.CREATED_ON,
          B.AUDIT_KEY,
          B.AUDIT_VALUE,
          B.MODIFIED_FROM_VALUE
     FROM SDATA_AUDIT_HISTORY a, SDATA_AUDIT_HISTORY_DETAIL B
    WHERE a.ACTION_ID = b.ACTION_ID AND B.MODIFIED_FROM_VALUE IS NOT NULL;
