--liquibase formatted sql
--changeset ${vr_owner_user}_CODE:VIEW_VW_AGE_EXCEPTIONS runOnChange:TRUE  failOnError:TRUE splitStatements:TRUE


  CREATE OR REPLACE FORCE VIEW "VW_AGE_EXCEPTIONS" ("ASOFDATE", "SOURCE_SYSTEM_ID", "INSTRUMENT_ID", "INSTRUMENT_TYPE", "PRICE", "QUANTITY", "FACTOR", "MARKET_VALUE", "MARKET_VALUE_USD", "LONG_SHORT", "PRODUCT_TYPE", "LEGAL_ENTITY_ID", "INSTRUMENT_ID_LEVEL2", "INSTRUMENT_TYPE_LEVEL2", "INSTRUMENT_ID_LEVEL3", "INSTRUMENT_TYPE_LEVEL3", "INSTRUMENT_ID_LEVEL4", "INSTRUMENT_TYPE_LEVEL4", "INSTRUMENT_ID_LEVEL5", "INSTRUMENT_TYPE_LEVEL5", "BOOK_ID", "FX_CURRENCY_ID", "NOTIONAL_CURRENCY_ID", "INSTRUMENT_DESCRIPTION", "MS_FLG", "MID_FLG") AS 
  SELECT ASOFDATE,
  SOURCE_SYSTEM_ID,
  INSTRUMENT_ID,
  INSTRUMENT_TYPE,
  PRICE,
  QUANTITY,
  FACTOR,
  MARKET_VALUE,
  MARKET_VALUE_USD,
  LONG_SHORT,
  PRODUCT_TYPE,
  LEGAL_ENTITY_ID,
  INSTRUMENT_ID_LEVEL2,
  INSTRUMENT_TYPE_LEVEL2,
  INSTRUMENT_ID_LEVEL3,
  INSTRUMENT_TYPE_LEVEL3,
  INSTRUMENT_ID_LEVEL4,
  INSTRUMENT_TYPE_LEVEL4,
  INSTRUMENT_ID_LEVEL5,
  INSTRUMENT_TYPE_LEVEL5,
  BOOK_ID,
  FX_CURRENCY_ID,
  NOTIONAL_CURRENCY_ID,
  INSTRUMENT_DESCRIPTION,
  MS_FLG,
  MID_FLG
FROM AGE_EXCEPTIONS;
