--liquibase formatted sql
--changeset ${vr_owner_user}_CODE:VIEW_VW_BOOK_HIERARCHY_MULTIMETRIC runOnChange:TRUE  failOnError:TRUE splitStatements:TRUE


  CREATE OR REPLACE FORCE VIEW "VW_BOOK_HIERARCHY_MULTIMETRIC" ("ASOFDATE", "BOOK_ID", "SOURCE_SYSTEM", "LEGAL_ENTITY", "GLOBAL_TRADER_BOOK_ID", "PROFIT_CENTER_ID", "COMMENTS", "DATA_SOURCE", "MI_LOCATION", "TRADING_UNIT", "VOLCKER_TRADING_DESK_FULL", "LOWEST_LEVEL_RPL_CODE", "LOWEST_LEVEL_RPL_FULL_NAME", "LOWEST_LEVEL_RPL", "CHARGE_REPORTING_UNIT_CODE", "CHARGE_REPORTING_UNIT", "CHARGE_REPORTING_PARENT_CODE", "CHARGE_REPORTING_PARENT", "UBR_LEVEL_1_ID", "UBR_LEVEL_1_NAME", "UBR_LEVEL_1_RPL_CODE", "UBR_LEVEL_2_ID", "UBR_LEVEL_2_NAME", "UBR_LEVEL_2_RPL_CODE", "UBR_LEVEL_3_ID", "UBR_LEVEL_3_NAME", "UBR_LEVEL_3_RPL_CODE", "UBR_LEVEL_4_ID", "UBR_LEVEL_4_NAME", "UBR_LEVEL_4_RPL_CODE", "UBR_LEVEL_5_ID", "UBR_LEVEL_5_NAME", "UBR_LEVEL_5_RPL_CODE", "UBR_LEVEL_6_ID", "UBR_LEVEL_6_NAME", "UBR_LEVEL_6_RPL_CODE", "UBR_LEVEL_7_ID", "UBR_LEVEL_7_NAME", "UBR_LEVEL_7_RPL_CODE", "UBR_LEVEL_8_ID", "UBR_LEVEL_8_NAME", "UBR_LEVEL_8_RPL_CODE", "UBR_LEVEL_9_ID", "UBR_LEVEL_9_NAME", "UBR_LEVEL_9_RPL_CODE", "UBR_LEVEL_10_ID", "UBR_LEVEL_10_NAME", "UBR_LEVEL_10_RPL_CODE", "UBR_LEVEL_11_ID", "UBR_LEVEL_11_NAME", "UBR_LEVEL_11_RPL_CODE", "UBR_LEVEL_12_ID", "UBR_LEVEL_12_NAME", "UBR_LEVEL_12_RPL_CODE", "UBR_LEVEL_13_ID", "UBR_LEVEL_13_NAME", "UBR_LEVEL_13_RPL_CODE", "UBR_LEVEL_14_ID", "UBR_LEVEL_14_NAME", "UBR_LEVEL_14_RPL_CODE", "DESK_LEVEL_1_ID", "DESK_LEVEL_1_NAME", "DESK_LEVEL_1_RPL_CODE", "DESK_LEVEL_2_ID", "DESK_LEVEL_2_NAME", "DESK_LEVEL_2_RPL_CODE", "DESK_LEVEL_3_ID", "DESK_LEVEL_3_NAME", "DESK_LEVEL_3_RPL_CODE", "DESK_LEVEL_4_ID", "DESK_LEVEL_4_NAME", "DESK_LEVEL_4_RPL_CODE", "DESK_LEVEL_5_ID", "DESK_LEVEL_5_NAME", "DESK_LEVEL_5_RPL_CODE", "PORTFOLIO_ID", "PORTFOLIO_NAME", "PORTFOLIO_RPL_CODE", "BUSINESS", "SUB_BUSINESS", "REGION", "SUBREGION") AS 
  SELECT Y.YEARDATE AS ASOFDATE,
          UPPER (B.BOOK_ID) AS BOOK_ID,
          B.SOURCE_SYSTEM,
          UPPER (B.LEGAL_ENTITY) AS LEGAL_ENTITY,
          UPPER (B.GLOBAL_TRADER_BOOK_ID) AS GLOBAL_TRADER_BOOK_ID,

          UPPER (B.PROFIT_CENTER_ID) AS PROFIT_CENTER_ID,
          UPPER (B.COMMENTS) AS COMMENTS,
          UPPER (B.DATA_SOURCE) AS DATA_SOURCE,
          UPPER (B.MI_LOCATION) AS MI_LOCATION,
          UPPER (B.VOLCKER_TRADING_DESK) AS TRADING_UNIT,
          UPPER (B.VOLCKER_TRADING_DESK_FULL) AS VOLCKER_TRADING_DESK_FULL,
          UPPER (B.LOWEST_LEVEL_RPL_CODE) AS LOWEST_LEVEL_RPL_CODE,
          UPPER (B.LOWEST_LEVEL_RPL_FULL_NAME) AS LOWEST_LEVEL_RPL_FULL_NAME,
          UPPER (B.LOWEST_LEVEL_RPL) AS LOWEST_LEVEL_RPL,
          UPPER (B.CHARGE_REPORTING_UNIT_CODE) AS CHARGE_REPORTING_UNIT_CODE,
          UPPER (B.CHARGE_REPORTING_UNIT) AS CHARGE_REPORTING_UNIT,
          UPPER (B.CHARGE_REPORTING_PARENT_CODE) AS CHARGE_REPORTING_PARENT_CODE, 
          UPPER (B.CHARGE_REPORTING_PARENT) AS CHARGE_REPORTING_PARENT,
          UPPER (B.UBR_LEVEL_1_ID) AS UBR_LEVEL_1_ID,
          UPPER (B.UBR_LEVEL_1_NAME) AS UBR_LEVEL_1_NAME,
          UPPER (B.UBR_LEVEL_1_RPL_CODE) AS UBR_LEVEL_1_RPL_CODE,
          UPPER (B.UBR_LEVEL_2_ID) AS UBR_LEVEL_2_ID,
          UPPER (B.UBR_LEVEL_2_NAME) AS UBR_LEVEL_2_NAME,
          UPPER (B.UBR_LEVEL_2_RPL_CODE) AS UBR_LEVEL_2_RPL_CODE,
          UPPER (B.UBR_LEVEL_3_ID) AS UBR_LEVEL_3_ID,
          UPPER (B.UBR_LEVEL_3_NAME) AS UBR_LEVEL_3_NAME,
          UPPER (B.UBR_LEVEL_3_RPL_CODE) AS UBR_LEVEL_3_RPL_CODE,
          UPPER (B.UBR_LEVEL_4_ID) AS UBR_LEVEL_4_ID,
          UPPER (B.UBR_LEVEL_4_NAME) AS UBR_LEVEL_4_NAME,
          UPPER (B.UBR_LEVEL_4_RPL_CODE) AS UBR_LEVEL_4_RPL_CODE,
          UPPER (B.UBR_LEVEL_5_ID) AS UBR_LEVEL_5_ID,
          UPPER (B.UBR_LEVEL_5_NAME) AS UBR_LEVEL_5_NAME,
          UPPER (B.UBR_LEVEL_5_RPL_CODE) AS UBR_LEVEL_5_RPL_CODE,
          UPPER (B.UBR_LEVEL_6_ID) AS UBR_LEVEL_6_ID,
          UPPER (B.UBR_LEVEL_6_NAME) AS UBR_LEVEL_6_NAME,
          UPPER (B.UBR_LEVEL_6_RPL_CODE) AS UBR_LEVEL_6_RPL_CODE,
          UPPER (B.UBR_LEVEL_7_ID) AS UBR_LEVEL_7_ID,

          UPPER (B.UBR_LEVEL_7_NAME) AS UBR_LEVEL_7_NAME,
          UPPER (B.UBR_LEVEL_7_RPL_CODE) AS UBR_LEVEL_7_RPL_CODE,
          UPPER (B.UBR_LEVEL_8_ID) AS UBR_LEVEL_8_ID,
          UPPER (B.UBR_LEVEL_8_NAME) AS UBR_LEVEL_8_NAME,
          UPPER (B.UBR_LEVEL_8_RPL_CODE) AS UBR_LEVEL_8_RPL_CODE,
          UPPER (B.UBR_LEVEL_9_ID) AS UBR_LEVEL_9_ID,
          UPPER (B.UBR_LEVEL_9_NAME) AS UBR_LEVEL_9_NAME,
          UPPER (B.UBR_LEVEL_9_RPL_CODE) AS UBR_LEVEL_9_RPL_CODE,
          UPPER (B.UBR_LEVEL_10_ID) AS UBR_LEVEL_10_ID,
          UPPER (B.UBR_LEVEL_10_NAME) AS UBR_LEVEL_10_NAME,
          UPPER (B.UBR_LEVEL_10_RPL_CODE) AS UBR_LEVEL_10_RPL_CODE,
          UPPER (B.UBR_LEVEL_11_ID) AS UBR_LEVEL_11_ID,
          UPPER (B.UBR_LEVEL_11_NAME) AS UBR_LEVEL_11_NAME,
          UPPER (B.UBR_LEVEL_11_RPL_CODE) AS UBR_LEVEL_11_RPL_CODE,
          UPPER (B.UBR_LEVEL_12_ID) AS UBR_LEVEL_12_ID,
          UPPER (B.UBR_LEVEL_12_NAME) AS UBR_LEVEL_12_NAME,
          UPPER (B.UBR_LEVEL_12_RPL_CODE) AS UBR_LEVEL_12_RPL_CODE,
          UPPER (B.UBR_LEVEL_13_ID) AS UBR_LEVEL_13_ID,
          UPPER (B.UBR_LEVEL_13_NAME) AS UBR_LEVEL_13_NAME,
          UPPER (B.UBR_LEVEL_13_RPL_CODE) AS UBR_LEVEL_13_RPL_CODE,
          UPPER (B.UBR_LEVEL_14_ID) AS UBR_LEVEL_14_ID,
          UPPER (B.UBR_LEVEL_14_NAME) AS UBR_LEVEL_14_NAME,
          UPPER (B.UBR_LEVEL_14_RPL_CODE) AS UBR_LEVEL_14_RPL_CODE,
          UPPER (B.DESK_LEVEL_1_ID) AS DESK_LEVEL_1_ID,
          UPPER (B.DESK_LEVEL_1_NAME) AS DESK_LEVEL_1_NAME,
          UPPER (B.DESK_LEVEL_1_RPL_CODE) AS DESK_LEVEL_1_RPL_CODE,
          UPPER (B.DESK_LEVEL_2_ID) AS DESK_LEVEL_2_ID,
          UPPER (B.DESK_LEVEL_2_NAME) AS DESK_LEVEL_2_NAME,
          UPPER (B.DESK_LEVEL_2_RPL_CODE) AS DESK_LEVEL_2_RPL_CODE,
          UPPER (B.DESK_LEVEL_3_ID) AS DESK_LEVEL_3_ID,
          UPPER (B.DESK_LEVEL_3_NAME) AS DESK_LEVEL_3_NAME,
          UPPER (B.DESK_LEVEL_3_RPL_CODE) AS DESK_LEVEL_3_RPL_CODE,

          UPPER (B.DESK_LEVEL_4_ID) AS DESK_LEVEL_4_ID,
          UPPER (B.DESK_LEVEL_4_NAME) AS DESK_LEVEL_4_NAME,
          UPPER (B.DESK_LEVEL_4_RPL_CODE) AS DESK_LEVEL_4_RPL_CODE,
          UPPER (B.DESK_LEVEL_5_ID) AS DESK_LEVEL_5_ID,
          UPPER (B.DESK_LEVEL_5_NAME) AS DESK_LEVEL_5_NAME,
          UPPER (B.DESK_LEVEL_5_RPL_CODE) AS DESK_LEVEL_5_RPL_CODE,
          UPPER (B.PORTFOLIO_ID) AS PORTFOLIO_ID,
          UPPER (B.PORTFOLIO_NAME) AS PORTFOLIO_NAME,
          UPPER (B.PORTFOLIO_RPL_CODE) AS PORTFOLIO_RPL_CODE,
          UPPER (B.BUSINESS) AS BUSINESS,
          UPPER (B.SUB_BUSINESS) AS SUB_BUSINESS,
          UPPER (B.REGION) AS REGION,
          UPPER (B.SUBREGION) AS SUBREGION
     FROM    BOOK_HIERARCHY_RPL B
          JOIN
             (  SELECT Y2.YEARDATE,
MAX (B2.ASOFDATE) AS MAX_ASOFDATE
                  FROM    (    SELECT TRUNC (SYSDATE) + 1 - ROWNUM AS YEARDATE
                                 FROM DUAL
                           CONNECT BY ROWNUM <= 365) Y2
                       JOIN
                          (SELECT DISTINCT ASOFDATE FROM BOOK_HIERARCHY_RPL) B2
                       ON B2.ASOFDATE <= Y2.YEARDATE
              GROUP BY Y2.YEARDATE) Y
          ON Y.MAX_ASOFDATE = B.ASOFDATE;
