--liquibase formatted sql
--changeset ${vr_owner_user}_CODE:VIEW_VW_BH_COUNT_DUPLICATES_ENR runOnChange:TRUE  failOnError:TRUE splitStatements:TRUE


  CREATE OR REPLACE FORCE VIEW "VW_BH_COUNT_DUPLICATES_ENR" ("ASOFDATE", "BOOK_ID", "SOURCE_SYSTEM", "GLOBAL_TRADER_BOOK_ID", "TRADING_UNIT", "VOLCKER_TRADING_DESK_FULL", "LOWEST_LEVEL_RPL_CODE", "LOWEST_LEVEL_RPL_FULL_NAME", "LOWEST_LEVEL_RPL", "CHARGE_REPORTING_UNIT_CODE", "CHARGE_REPORTING_UNIT", "CHARGE_REPORTING_PARENT_CODE", "CHARGE_REPORTING_PARENT", "UBR_LEVEL_1_ID", "UBR_LEVEL_1_NAME", "UBR_LEVEL_1_RPL_CODE", "UBR_LEVEL_2_ID", "UBR_LEVEL_2_NAME", "UBR_LEVEL_2_RPL_CODE", "UBR_LEVEL_3_ID", "UBR_LEVEL_3_NAME", "UBR_LEVEL_3_RPL_CODE", "UBR_LEVEL_4_ID", "UBR_LEVEL_4_NAME", "UBR_LEVEL_4_RPL_CODE", "UBR_LEVEL_5_ID", "UBR_LEVEL_5_NAME", "UBR_LEVEL_5_RPL_CODE", "UBR_LEVEL_6_ID", "UBR_LEVEL_6_NAME", "UBR_LEVEL_6_RPL_CODE", "UBR_LEVEL_7_ID", "UBR_LEVEL_7_NAME", "UBR_LEVEL_7_RPL_CODE", "UBR_LEVEL_8_ID", "UBR_LEVEL_8_NAME", "UBR_LEVEL_8_RPL_CODE", "UBR_LEVEL_9_ID", "UBR_LEVEL_9_NAME", "UBR_LEVEL_9_RPL_CODE", "UBR_LEVEL_10_ID", "UBR_LEVEL_10_NAME", "UBR_LEVEL_10_RPL_CODE", "UBR_LEVEL_11_ID", "UBR_LEVEL_11_NAME", "UBR_LEVEL_11_RPL_CODE", "UBR_LEVEL_12_ID", "UBR_LEVEL_12_NAME", "UBR_LEVEL_12_RPL_CODE", "UBR_LEVEL_13_ID", "UBR_LEVEL_13_NAME", "UBR_LEVEL_13_RPL_CODE", "UBR_LEVEL_14_ID", "UBR_LEVEL_14_NAME", "UBR_LEVEL_14_RPL_CODE", "DESK_LEVEL_1_ID", "DESK_LEVEL_1_NAME", "DESK_LEVEL_1_RPL_CODE", "DESK_LEVEL_2_ID", "DESK_LEVEL_2_NAME", "DESK_LEVEL_2_RPL_CODE", "DESK_LEVEL_3_ID", "DESK_LEVEL_3_NAME", "DESK_LEVEL_3_RPL_CODE", "DESK_LEVEL_4_ID", "DESK_LEVEL_4_NAME", "DESK_LEVEL_4_RPL_CODE", "DESK_LEVEL_5_ID", "DESK_LEVEL_5_NAME", "DESK_LEVEL_5_RPL_CODE", "PORTFOLIO_ID", "PORTFOLIO_NAME", "PORTFOLIO_RPL_CODE", "BUSINESS", "SUB_BUSINESS", "NUM_BOOKS", "REGION", "SUBREGION", "VOLCKER_TRADING_DESK", "MI_LOCATION", "LEGAL_ENTITY", "NUM_GTBI", "LEGAL_ENTITY_CODE", "NON_VTD_CODE", "NON_VTD_NAME", "NON_VTD_RPL_CODE", "NON_VTD_EXCLUSION_TYPE", "REGULATORY_REPORTING_TREATMENT", "VOLCKER_REPORTABLE_FLAG", "NON_VTD_DIVISION", "NON_VTD_PVF", "NON_VTD_BUSINESS") AS 
  SELECT B1.ASOFDATE,

          UPPER(B1.BOOK_ID) AS BOOK_ID,
          B1.SOURCE_SYSTEM_ID AS SOURCE_SYSTEM,
          B2.GLOBAL_TRADER_BOOK_ID,
          B2.VOLCKER_TRADING_DESK AS TRADING_UNIT,
          B2.VOLCKER_TRADING_DESK_FULL,
          B2.LOWEST_LEVEL_RPL_CODE,
          B2.LOWEST_LEVEL_RPL_FULL_NAME,
          B2.LOWEST_LEVEL_RPL,
          B2.CHARGE_REPORTING_UNIT_CODE,
          B2.CHARGE_REPORTING_UNIT,
          B2.CHARGE_REPORTING_PARENT_CODE,
          B2.CHARGE_REPORTING_PARENT,
          B2.UBR_LEVEL_1_ID,
          B2.UBR_LEVEL_1_NAME,
          B2.UBR_LEVEL_1_RPL_CODE,
          B2.UBR_LEVEL_2_ID,
          B2.UBR_LEVEL_2_NAME,
          B2.UBR_LEVEL_2_RPL_CODE,
          B2.UBR_LEVEL_3_ID,
          B2.UBR_LEVEL_3_NAME,
          B2.UBR_LEVEL_3_RPL_CODE,
          B2.UBR_LEVEL_4_ID,
          B2.UBR_LEVEL_4_NAME,
          B2.UBR_LEVEL_4_RPL_CODE,
          B2.UBR_LEVEL_5_ID,
          B2.UBR_LEVEL_5_NAME,
          B2.UBR_LEVEL_5_RPL_CODE,
          B2.UBR_LEVEL_6_ID,
          B2.UBR_LEVEL_6_NAME,
          B2.UBR_LEVEL_6_RPL_CODE,
          B2.UBR_LEVEL_7_ID,
          B2.UBR_LEVEL_7_NAME,
          B2.UBR_LEVEL_7_RPL_CODE,
          B2.UBR_LEVEL_8_ID,
          B2.UBR_LEVEL_8_NAME,
          B2.UBR_LEVEL_8_RPL_CODE,
          B2.UBR_LEVEL_9_ID,
          B2.UBR_LEVEL_9_NAME,
          B2.UBR_LEVEL_9_RPL_CODE,
          B2.UBR_LEVEL_10_ID,
          B2.UBR_LEVEL_10_NAME,
          B2.UBR_LEVEL_10_RPL_CODE,
          B2.UBR_LEVEL_11_ID,
          B2.UBR_LEVEL_11_NAME,
          B2.UBR_LEVEL_11_RPL_CODE,
          B2.UBR_LEVEL_12_ID,
          B2.UBR_LEVEL_12_NAME,
          B2.UBR_LEVEL_12_RPL_CODE,
          B2.UBR_LEVEL_13_ID,
          B2.UBR_LEVEL_13_NAME,
          B2.UBR_LEVEL_13_RPL_CODE,
          B2.UBR_LEVEL_14_ID,
          B2.UBR_LEVEL_14_NAME,
          B2.UBR_LEVEL_14_RPL_CODE,
          B2.DESK_LEVEL_1_ID,
          B2.DESK_LEVEL_1_NAME,
          B2.DESK_LEVEL_1_RPL_CODE,
          B2.DESK_LEVEL_2_ID,
          B2.DESK_LEVEL_2_NAME,

          B2.DESK_LEVEL_2_RPL_CODE,
          B2.DESK_LEVEL_3_ID,
          B2.DESK_LEVEL_3_NAME,
          B2.DESK_LEVEL_3_RPL_CODE,
          B2.DESK_LEVEL_4_ID,
          B2.DESK_LEVEL_4_NAME,
          B2.DESK_LEVEL_4_RPL_CODE,
          B2.DESK_LEVEL_5_ID,
          B2.DESK_LEVEL_5_NAME,
          B2.DESK_LEVEL_5_RPL_CODE,
          B2.PORTFOLIO_ID,
          B2.PORTFOLIO_NAME,
          B2.PORTFOLIO_RPL_CODE,
          B2.BUSINESS,
          B2.SUB_BUSINESS,
          COUNT(B1.BOOK_ID) OVER (PARTITION by B1.ASOFDATE, B1.BOOK_ID, B1.SOURCE_SYSTEM_ID) AS NUM_BOOKS, 
          B2.REGION,
          B2.SUBREGION,
          B2.VOLCKER_TRADING_DESK,
          B2.MI_LOCATION,
          B2.LEGAL_ENTITY,
          COUNT(B2.GLOBAL_TRADER_BOOK_ID) OVER (PARTITION by B1.ASOFDATE, B1.BOOK_ID, B1.SOURCE_SYSTEM_ID) AS NUM_GTBI,
          --start GBSVR-29167
          B2.LEGAL_ENTITY_CODE,
          --end GBSVR-29167
          --start GBSVR-28872
          B2.NON_VTD_CODE,
          B2.NON_VTD_NAME,
          B2.NON_VTD_RPL_CODE,
          B2.NON_VTD_EXCLUSION_TYPE,
          B2.REGULATORY_REPORTING_TREATMENT,
          --end GBSVR-28872
          --start GBSVR-30043
          B2.VOLCKER_REPORTABLE_FLAG,
          --end GBSVR-30043
           --start GBSVR-30224
          B2.NON_VTD_DIVISION,  
          B2.NON_VTD_PVF, 
          B2.NON_VTD_BUSINESS 
          --end GBSVR-30224
     FROM (  SELECT B.ASOFDATE,
                    B.BOOK_ID,
                    SS3.SOURCE_SYSTEM_ID,
                    NVL(MAX(SS2.SOURCE_SYSTEM_ID),
'[NULL]') ORIGINAL_SS                    
               FROM BOOK_HIERARCHY_RPL B
                    LEFT JOIN SOURCE_SYSTEM SS
                       ON SS.SOURCE_SYSTEM_ID = B.SOURCE_SYSTEM
                    LEFT JOIN SOURCE_SYSTEM SS2
                       ON SS2.SOURCE_SYSTEM_CRDS_NAME =
                             SS.SOURCE_SYSTEM_CRDS_NAME
                          AND SS2.REGION_ID = SS.REGION_ID
                    LEFT JOIN SOURCE_SYSTEM SS3
                       ON NVL(SS2.SOURCE_SYSTEM_ID,SS3.SOURCE_SYSTEM_ID) = SS3.SOURCE_SYSTEM_ID
           GROUP BY B.ASOFDATE, B.BOOK_ID, SS3.SOURCE_SYSTEM_ID) B1
          JOIN (SELECT B.*,NVL(SSS2.SOURCE_SYSTEM_ID,
'[NULL]') ORIGINAL_SS 
		          FROM BOOK_HIERARCHY_RPL B
                       LEFT JOIN SOURCE_SYSTEM SSS
                          ON SSS.SOURCE_SYSTEM_ID = B.SOURCE_SYSTEM
                       LEFT JOIN SOURCE_SYSTEM SSS2
                          ON SSS2.SOURCE_SYSTEM_CRDS_NAME = SSS.SOURCE_SYSTEM_CRDS_NAME
                         AND SSS2.REGION_ID = SSS.REGION_ID) B2
             ON B2.ASOFDATE = B1.ASOFDATE AND B2.BOOK_ID = B1.BOOK_ID AND B2.ORIGINAL_SS = B1.ORIGINAL_SS;
