--liquibase formatted sql
--changeset ${vr_owner_user}_CODE:VIEW_VW_BH_STAGING runOnChange:TRUE  failOnError:TRUE splitStatements:TRUE


  CREATE OR REPLACE FORCE VIEW "VW_BH_STAGING" ("ID", "ASOFDATE", "BOOK_ID", "VOLCKER_TRADING_DESK", "VOLCKER_TRADING_DESK_FULL", "LOWEST_LEVEL_RPL_CODE", "LOWEST_LEVEL_RPL_FULL_NAME", "LOWEST_LEVEL_RPL", "SOURCE_SYSTEM", "LEGAL_ENTITY", "GLOBAL_TRADER_BOOK_ID", "PROFIT_CENTER_ID", "COMMENTS", "DATA_SOURCE", "CREATE_DATE", "LAST_MODIFIED_DATE", "CHARGE_REPORTING_UNIT_CODE", "CHARGE_REPORTING_UNIT", "CHARGE_REPORTING_PARENT_CODE", "CHARGE_REPORTING_PARENT", "MI_LOCATION", "UBR_LEVEL_1_ID", "UBR_LEVEL_1_NAME", "UBR_LEVEL_1_RPL_CODE", "UBR_LEVEL_2_ID", "UBR_LEVEL_2_NAME", "UBR_LEVEL_2_RPL_CODE", "UBR_LEVEL_3_ID", "UBR_LEVEL_3_NAME", "UBR_LEVEL_3_RPL_CODE", "UBR_LEVEL_4_ID", "UBR_LEVEL_4_NAME", "UBR_LEVEL_4_RPL_CODE", "UBR_LEVEL_5_ID", "UBR_LEVEL_5_NAME", "UBR_LEVEL_5_RPL_CODE", "UBR_LEVEL_6_ID", "UBR_LEVEL_6_NAME", "UBR_LEVEL_6_RPL_CODE", "UBR_LEVEL_7_ID", "UBR_LEVEL_7_NAME", "UBR_LEVEL_7_RPL_CODE", "UBR_LEVEL_8_ID", "UBR_LEVEL_8_NAME", "UBR_LEVEL_8_RPL_CODE", "UBR_LEVEL_9_ID", "UBR_LEVEL_9_NAME", "UBR_LEVEL_9_RPL_CODE", "UBR_LEVEL_10_ID", "UBR_LEVEL_10_NAME", "UBR_LEVEL_10_RPL_CODE", "UBR_LEVEL_11_ID", "UBR_LEVEL_11_NAME", "UBR_LEVEL_11_RPL_CODE", "UBR_LEVEL_12_ID", "UBR_LEVEL_12_NAME", "UBR_LEVEL_12_RPL_CODE", "UBR_LEVEL_13_ID", "UBR_LEVEL_13_NAME", "UBR_LEVEL_13_RPL_CODE", "UBR_LEVEL_14_ID", "UBR_LEVEL_14_NAME", "UBR_LEVEL_14_RPL_CODE", "DESK_LEVEL_1_ID", "DESK_LEVEL_1_NAME", "DESK_LEVEL_1_RPL_CODE", "DESK_LEVEL_2_ID", "DESK_LEVEL_2_NAME", "DESK_LEVEL_2_RPL_CODE", "DESK_LEVEL_3_ID", "DESK_LEVEL_3_NAME", "DESK_LEVEL_3_RPL_CODE", "DESK_LEVEL_4_ID", "DESK_LEVEL_4_NAME", "DESK_LEVEL_4_RPL_CODE", "DESK_LEVEL_5_ID", "DESK_LEVEL_5_NAME", "DESK_LEVEL_5_RPL_CODE", "PORTFOLIO_ID", "PORTFOLIO_NAME", "PORTFOLIO_RPL_CODE", "BUSINESS", "SUB_BUSINESS", "CREATE_USER", "LAST_MODIFICATION_USER", "REGION", "SUBREGION", "OVERRIDDEN_FLAG", "ACTIVE_FLAG", "EMERGENCY_FLAG", "BH_INTERMEDIARY_ID", "APPROVER_USER", "APPROVAL_DATE", "RPL_LOAD", 
  -- GBSVR-33754 Start: CFBU decommissioning
  -- GBSVR-33754 End:   CFBU decommissioning
  "ACC_TREAT_CATEGORY", "PRIMARY_TRADER", "PRIMARY_BOOK_RUNNER", "PRIMARY_FINCON", "PRIMARY_MOESCALATION", "LEGAL_ENTITY_CODE", "BOOK_FUNCTION_CODE", "REGULATORY_REPORTING_TREATMENT", "UBR_MA_CODE", "HIERARCHY_UBR_NODENAME", "PROFIT_CENTRE_NAME", "NON_VTD_CODE", "NON_VTD_NAME", "NON_VTD_RPL_CODE", "NON_VTD_EXCLUSION_TYPE", "VOLCKER_REPORTABLE_FLAG", "NON_VTD_DIVISION", "NON_VTD_PVF", "NON_VTD_BUSINESS") AS 
  SELECT
ROWNUM AS ID,
ASOFDATE,                         
BOOK_ID,                        
VOLCKER_TRADING_DESK,           
VOLCKER_TRADING_DESK_FULL,                
LOWEST_LEVEL_RPL_CODE,                     
LOWEST_LEVEL_RPL_FULL_NAME,                
LOWEST_LEVEL_RPL,                         
SOURCE_SYSTEM,                            
LEGAL_ENTITY,                             
GLOBAL_TRADER_BOOK_ID,                   
PROFIT_CENTER_ID,                    
COMMENTS,                                  
DATA_SOURCE,                               
CREATE_DATE,                               
LAST_MODIFIED_DATE,                        
CHARGE_REPORTING_UNIT_CODE,                
CHARGE_REPORTING_UNIT,                     
CHARGE_REPORTING_PARENT_CODE,              
CHARGE_REPORTING_PARENT,                  
MI_LOCATION,                               
UBR_LEVEL_1_ID,                            
UBR_LEVEL_1_NAME,                          
UBR_LEVEL_1_RPL_CODE,                     
UBR_LEVEL_2_ID,                           
UBR_LEVEL_2_NAME,                          
UBR_LEVEL_2_RPL_CODE,                      
UBR_LEVEL_3_ID,                            
UBR_LEVEL_3_NAME,                          
UBR_LEVEL_3_RPL_CODE,                      
UBR_LEVEL_4_ID,                            
UBR_LEVEL_4_NAME,                          
UBR_LEVEL_4_RPL_CODE,                      
UBR_LEVEL_5_ID,                           
UBR_LEVEL_5_NAME,                          
UBR_LEVEL_5_RPL_CODE,                      
UBR_LEVEL_6_ID,
UBR_LEVEL_6_NAME,                          
UBR_LEVEL_6_RPL_CODE ,                     
UBR_LEVEL_7_ID,                           
UBR_LEVEL_7_NAME,                      
UBR_LEVEL_7_RPL_CODE,                      
UBR_LEVEL_8_ID,                            
UBR_LEVEL_8_NAME,                          
UBR_LEVEL_8_RPL_CODE,                      
UBR_LEVEL_9_ID,                            
UBR_LEVEL_9_NAME,                          
UBR_LEVEL_9_RPL_CODE,                      
UBR_LEVEL_10_ID,                          
UBR_LEVEL_10_NAME,                         
UBR_LEVEL_10_RPL_CODE,                     
UBR_LEVEL_11_ID,                           
UBR_LEVEL_11_NAME,                        
UBR_LEVEL_11_RPL_CODE,                     
UBR_LEVEL_12_ID,                           
UBR_LEVEL_12_NAME,                         
UBR_LEVEL_12_RPL_CODE,                     
UBR_LEVEL_13_ID,                           
UBR_LEVEL_13_NAME,                         
UBR_LEVEL_13_RPL_CODE,                     
UBR_LEVEL_14_ID,                           
UBR_LEVEL_14_NAME,                         
UBR_LEVEL_14_RPL_CODE,                     
DESK_LEVEL_1_ID,                           
DESK_LEVEL_1_NAME,                         
DESK_LEVEL_1_RPL_CODE,                     
DESK_LEVEL_2_ID,                           
DESK_LEVEL_2_NAME,                         
DESK_LEVEL_2_RPL_CODE,                     
DESK_LEVEL_3_ID,                           
DESK_LEVEL_3_NAME,                         
DESK_LEVEL_3_RPL_CODE,                     
DESK_LEVEL_4_ID,                           
DESK_LEVEL_4_NAME,                         
DESK_LEVEL_4_RPL_CODE,                     
DESK_LEVEL_5_ID,                           
DESK_LEVEL_5_NAME,                         
DESK_LEVEL_5_RPL_CODE,                    
PORTFOLIO_ID,                              
PORTFOLIO_NAME,                            
PORTFOLIO_RPL_CODE,                        
BUSINESS,
SUB_BUSINESS,                              
CREATE_USER,                                
LAST_MODIFICATION_USER,                     
REGION,                                    
SUBREGION,                                 
OVERRIDDEN_FLAG,                         
ACTIVE_FLAG,                               
EMERGENCY_FLAG,                            
BH_INTERMEDIARY_ID,                           
APPROVER_USER,                              
APPROVAL_DATE,                           
RPL_LOAD,                                  
-- GBSVR-33754 Start: CFBU decommissioning
-- GBSVR-33754 End:   CFBU decommissioning
ACC_TREAT_CATEGORY,
PRIMARY_TRADER,
PRIMARY_BOOK_RUNNER,
PRIMARY_FINCON,
PRIMARY_MOESCALATION,
LEGAL_ENTITY_CODE,
BOOK_FUNCTION_CODE,
REGULATORY_REPORTING_TREATMENT,
UBR_MA_CODE, 
HIERARCHY_UBR_NODENAME,
PROFIT_CENTRE_NAME,
NON_VTD_CODE,
NON_VTD_NAME,
NON_VTD_RPL_CODE ,
NON_VTD_EXCLUSION_TYPE,
VOLCKER_REPORTABLE_FLAG,
NON_VTD_DIVISION,  
NON_VTD_PVF,
NON_VTD_BUSINESS 
FROM BH_STAGING;
