--liquibase formatted sql
--changeset ${vr_owner_user}_CODE:VIEW_VW_CHARGE_EXEMPTIONS runOnChange:TRUE  failOnError:TRUE splitStatements:TRUE


  CREATE OR REPLACE FORCE VIEW "VW_CHARGE_EXEMPTIONS" ("DATE_VALUE", "CEID", "CEDESCRIPTION", "EXEMPTION_TYPE", "VOLCKER_TRADING_DESK", "VOLCKER_TRADING_DESK_FULL", "LOWEST_LEVEL_RPL_CODE", "LOWEST_LEVEL_RPL_FULL_NAME", "LOWEST_LEVEL_RPL_RPL", "CHARGE_REPORT_UNIT_CODE", "CHARGE_REPORT_UNIT", "CHARGE_REPORT_UNIT_PARENT_CODE", "CHARGE_REPORT_UNIT_PARENT", "LONGSHORT", "UBR_LEVEL_1_RPL", "UBR_LEVEL_2_RPL", "UBR_LEVEL_3_RPL", "UBR_LEVEL_4_RPL", "UBR_LEVEL_5_RPL", "UBR_LEVEL_6_RPL", "UBR_LEVEL_7_RPL", "UBR_LEVEL_8_RPL", "UBR_LEVEL_9_RPL", "UBR_LEVEL_10_RPL", "UBR_LEVEL_11_RPL", "UBR_LEVEL_12_RPL", "UBR_LEVEL_13_RPL", "UBR_LEVEL_14_RPL", "DESK_LEVEL_1_RPL", "DESK_LEVEL_2_RPL", "DESK_LEVEL_3_RPL", "DESK_LEVEL_4_RPL", "DESK_LEVEL_5_RPL", "PORTFOLIO_RPL", "TRADING_BOOK", "PRODUCT_TYPE", "INSTRUMENT_TYPE", "INSTRUMENT_ID", "B0TO30_FLG", "B31TO60_FLG", "B61TO90_FLG", "B91TO180_FLG", "B181TO360_FLG", "B361_FLG", "EXEMPTION_DATE", "DATE_LAST_RECERT", "NEXT_RECERT_DUE_DATE") AS 
  SELECT Y.YEARDATE AS DATE_VALUE,
C.CEID,
C.CEDESCRIPTION,
C.EXEMPTION_TYPE,
C.VOLCKER_TRADING_DESK,
C.VOLCKER_TRADING_DESK_FULL,
C.LOWEST_LEVEL_RPL_CODE,
C.LOWEST_LEVEL_RPL_FULL_NAME,
C.LOWEST_LEVEL_RPL_RPL,
C.CHARGE_REPORT_UNIT_CODE,
C.CHARGE_REPORT_UNIT,
C.CHARGE_REPORT_UNIT_PARENT_CODE,
C.CHARGE_REPORT_UNIT_PARENT,
C.LONGSHORT,
C.UBR_LEVEL_1_RPL,
C.UBR_LEVEL_2_RPL,
C.UBR_LEVEL_3_RPL,
C.UBR_LEVEL_4_RPL,
C.UBR_LEVEL_5_RPL,
C.UBR_LEVEL_6_RPL,
C.UBR_LEVEL_7_RPL,
C.UBR_LEVEL_8_RPL,
C.UBR_LEVEL_9_RPL,
C.UBR_LEVEL_10_RPL,
C.UBR_LEVEL_11_RPL,
C.UBR_LEVEL_12_RPL,
C.UBR_LEVEL_13_RPL,
C.UBR_LEVEL_14_RPL,
C.DESK_LEVEL_1_RPL,
C.DESK_LEVEL_2_RPL,
C.DESK_LEVEL_3_RPL,
C.DESK_LEVEL_4_RPL,
C.DESK_LEVEL_5_RPL,
C.PORTFOLIO_RPL,
C.TRADING_BOOK,
C.PRODUCT_TYPE,
C.INSTRUMENT_TYPE,
C.INSTRUMENT_ID,
C.B0TO30_FLG,
C.B31TO60_FLG,
C.B61TO90_FLG,
C.B91TO180_FLG,
C.B181TO360_FLG,
C.B361_FLG,
C.EXEMPTION_DATE,
C.DATE_LAST_RECERT,
C.NEXT_RECERT_DUE_DATE
FROM CHARGE_EXEMPTIONS C
JOIN (SELECT Y2.YEARDATE,

MAX (C2.EXEMPTION_DATE) AS MAX_EXEMPTION_DATE
FROM (SELECT TRUNC (SYSDATE) + 1 - ROWNUM AS YEARDATE
FROM DUAL
CONNECT BY ROWNUM <= 365) Y2
JOIN (SELECT DISTINCT EXEMPTION_DATE
FROM CHARGE_EXEMPTIONS) C2
ON C2.EXEMPTION_DATE <= Y2.YEARDATE
GROUP BY Y2.YEARDATE) Y
ON Y.MAX_EXEMPTION_DATE = C.EXEMPTION_DATE;
