--liquibase formatted sql
--changeset ${vr_owner_user}_CODE:VIEW_VW_CHARGE_SCHEDULING runOnChange:TRUE  failOnError:TRUE splitStatements:TRUE


  CREATE OR REPLACE FORCE VIEW "VW_CHARGE_SCHEDULING" ("DATE_VALUE", "CSID", "BUCKET_0_30", "BUCKET_31_60", "BUCKET_61_90", "BUCKET_91_180", "BUCKET_181_360", "BUCKET_361") AS 
  SELECT DATE_VALUE, CSID, BUCKET_0_30, BUCKET_31_60, BUCKET_61_90, BUCKET_91_180, BUCKET_181_360, BUCKET_361
FROM
  (WITH DATES AS
  (SELECT ROWNUM POSITION,
    TO_DATE(SYSDATE + 1 - Level, 'DD/MM/RRRR') DATE_VALUE
  FROM DUAL
    CONNECT BY Level <= 365
  )
SELECT D.DATE_VALUE,
  CSID, BUCKET_0_30, BUCKET_31_60, BUCKET_61_90, BUCKET_91_180, BUCKET_181_360, BUCKET_361,
  DENSE_RANK() OVER (PARTITION BY D.DATE_VALUE ORDER BY B.SCHEDULING_DATE DESC) RANKING
FROM CHARGE_SCHEDULING B,
  DATES D
WHERE B.SCHEDULING_DATE <= D.DATE_VALUE
  )
WHERE RANKING = 1;
