--liquibase formatted sql
--changeset ${vr_owner_user}_CODE:VIEW_VW_SOURCE_SYSTEM runOnChange:TRUE  failOnError:TRUE splitStatements:TRUE


  CREATE OR REPLACE FORCE VIEW "VW_SOURCE_SYSTEM" ("METRIC_ID", "SOURCE_SYSTEM_ID", "REGION_ID", "LAST_LOAD", "NEXT_LOAD", "AFTER_NEXT_LOAD", "BH_BUSINESS", "BH_SUB_BUSINESS", "BH_TRADING_UNIT", "SYSTEM_FOLDER", "REGION_FOLDER", "SYSTEM_FOLDER_AUX", "NUM_REDUCE_TASK", "MAPRED_CHILD_JAVA_OPTS", "IO_SORT_MB", "CFTRFILE", "SOURCE_SYSTEM_CRDS_NAME", "BH_VOLCKER_TRADING_DESK", "BH_VOLCKER_TRADING_DESK_FULL", "BH_LOWEST_LEVEL_RPL_CODE", "BH_LOWEST_LEVEL_RPL_FULL_NAME", "BH_LOWEST_LEVEL_RPL", "BH_CHARGE_REPORT_UNIT_CODE", "BH_CHARGE_REPORT_UNIT", "BH_CHARGE_REPORT_PARENT_CODE", "BH_CHARGE_REPORT_PARENT", "BH_UBR_LEVEL_1_ID", "BH_UBR_LEVEL_1_NAME", "BH_UBR_LEVEL_1_RPL_CODE", "BH_UBR_LEVEL_2_ID", "BH_UBR_LEVEL_2_NAME", "BH_UBR_LEVEL_2_RPL_CODE", "BH_UBR_LEVEL_3_ID", "BH_UBR_LEVEL_3_NAME", "BH_UBR_LEVEL_3_RPL_CODE", "BH_UBR_LEVEL_4_ID", "BH_UBR_LEVEL_4_NAME", "BH_UBR_LEVEL_4_RPL_CODE", "BH_UBR_LEVEL_5_ID", "BH_UBR_LEVEL_5_NAME", "BH_UBR_LEVEL_5_RPL_CODE", "BH_UBR_LEVEL_6_ID", "BH_UBR_LEVEL_6_NAME", "BH_UBR_LEVEL_6_RPL_CODE", "BH_UBR_LEVEL_7_ID", "BH_UBR_LEVEL_7_NAME", "BH_UBR_LEVEL_7_RPL_CODE", "BH_UBR_LEVEL_8_ID", "BH_UBR_LEVEL_8_NAME", "BH_UBR_LEVEL_8_RPL_CODE", "BH_UBR_LEVEL_9_ID", "BH_UBR_LEVEL_9_NAME", "BH_UBR_LEVEL_9_RPL_CODE", "BH_UBR_LEVEL_10_ID", "BH_UBR_LEVEL_10_NAME", "BH_UBR_LEVEL_10_RPL_CODE", "BH_UBR_LEVEL_11_ID", "BH_UBR_LEVEL_11_NAME", "BH_UBR_LEVEL_11_RPL_CODE", "BH_UBR_LEVEL_12_ID", "BH_UBR_LEVEL_12_NAME", "BH_UBR_LEVEL_12_RPL_CODE", "BH_UBR_LEVEL_13_ID", "BH_UBR_LEVEL_13_NAME", "BH_UBR_LEVEL_13_RPL_CODE", "BH_UBR_LEVEL_14_ID", "BH_UBR_LEVEL_14_NAME", "BH_UBR_LEVEL_14_RPL_CODE", "BH_DESK_LEVEL_1_ID", "BH_DESK_LEVEL_1_NAME", "BH_DESK_LEVEL_1_RPL_CODE", "BH_DESK_LEVEL_2_ID", "BH_DESK_LEVEL_2_NAME", "BH_DESK_LEVEL_2_RPL_CODE", "BH_DESK_LEVEL_3_ID", "BH_DESK_LEVEL_3_NAME", "BH_DESK_LEVEL_3_RPL_CODE", "BH_DESK_LEVEL_4_ID", "BH_DESK_LEVEL_4_NAME", "BH_DESK_LEVEL_4_RPL_CODE", "BH_DESK_LEVEL_5_ID", "BH_DESK_LEVEL_5_NAME", "BH_DESK_LEVEL_5_RPL_CODE",
"BH_PORTFOLIO_ID", "BH_PORTFOLIO_NAME", "BH_PORTFOLIO_RPL_CODE") AS 
  SELECT 'SOURCE_SYSTEM' metric_id,
          ss.SOURCE_SYSTEM_ID,
          ss.REGION_ID,
          NVL (ss.AGE_HADOOP_LASTLOAD, SYSDATE - 2) last_load,
          NVL (ss.AGE_HADOOP_NEXTLOAD, SYSDATE - 1) next_load,
          DECODE (
             ss.AGE_HADOOP_NEXTLOAD,
             NULL, SYSDATE,
             ss.AGE_HADOOP_NEXTLOAD
             + DECODE (TO_CHAR (ss.AGE_HADOOP_NEXTLOAD + 1, 'd'),
                       6, 3,
                       7, 2,
                       1))
             after_next_load,
          ss.BH_BUSINESS,
          ss.BH_SUB_BUSINESS,
          ss.BH_TRADING_UNIT,
          ss.SYSTEM_FOLDER,
          ss.REGION_FOLDER,
          ss.SYSTEM_FOLDER_AUX,
          ss.NUM_REDUCE_TASK,
          ss.MAPRED_CHILD_JAVA_OPTS,
          ss.IO_SORT_MB,
          ss.cftrFile,
          ss.SOURCE_SYSTEM_CRDS_NAME,
          ssbh.bh_volcker_trading_desk,
          ssbh.bh_volcker_trading_desk_full,
          ssbh.bh_lowest_level_rpl_code,
          ssbh.bh_lowest_level_rpl_full_name,
          ssbh.bh_lowest_level_rpl,
          ssbh.bh_charge_report_unit_code,
          ssbh.bh_charge_report_unit,
          ssbh.bh_charge_report_parent_code,
          ssbh.bh_charge_report_parent,
          ssbh.bh_ubr_level_1_id,
          ssbh.bh_ubr_level_1_name,
          ssbh.bh_ubr_level_1_rpl_code,
          ssbh.bh_ubr_level_2_id,
          ssbh.bh_ubr_level_2_name,
          ssbh.bh_ubr_level_2_rpl_code,
          ssbh.bh_ubr_level_3_id,
          ssbh.bh_ubr_level_3_name,
          ssbh.bh_ubr_level_3_rpl_code,
          ssbh.bh_ubr_level_4_id,
          ssbh.bh_ubr_level_4_name,
          ssbh.bh_ubr_level_4_rpl_code,
          ssbh.bh_ubr_level_5_id,
          ssbh.bh_ubr_level_5_name,
          ssbh.bh_ubr_level_5_rpl_code,
          ssbh.bh_ubr_level_6_id,
          ssbh.bh_ubr_level_6_name,
          ssbh.bh_ubr_level_6_rpl_code,
          ssbh.bh_ubr_level_7_id,

          ssbh.bh_ubr_level_7_name,
          ssbh.bh_ubr_level_7_rpl_code,
          ssbh.bh_ubr_level_8_id,
          ssbh.bh_ubr_level_8_name,
          ssbh.bh_ubr_level_8_rpl_code,
          ssbh.bh_ubr_level_9_id,
          ssbh.bh_ubr_level_9_name,
          ssbh.bh_ubr_level_9_rpl_code,
          ssbh.bh_ubr_level_10_id,
          ssbh.bh_ubr_level_10_name,
          ssbh.bh_ubr_level_10_rpl_code,
          ssbh.bh_ubr_level_11_id,
          ssbh.bh_ubr_level_11_name,
          ssbh.bh_ubr_level_11_rpl_code,
          ssbh.bh_ubr_level_12_id,
          ssbh.bh_ubr_level_12_name,
          ssbh.bh_ubr_level_12_rpl_code,
          ssbh.bh_ubr_level_13_id,
          ssbh.bh_ubr_level_13_name,
          ssbh.bh_ubr_level_13_rpl_code,
          ssbh.bh_ubr_level_14_id,
          ssbh.bh_ubr_level_14_name,
          ssbh.bh_ubr_level_14_rpl_code,
          ssbh.bh_desk_level_1_id,
          ssbh.bh_desk_level_1_name,
          ssbh.bh_desk_level_1_rpl_code,
          ssbh.bh_desk_level_2_id,
          ssbh.bh_desk_level_2_name,
          ssbh.bh_desk_level_2_rpl_code,
          ssbh.bh_desk_level_3_id,
          ssbh.bh_desk_level_3_name,
          ssbh.bh_desk_level_3_rpl_code,
          ssbh.bh_desk_level_4_id,
          ssbh.bh_desk_level_4_name,
          ssbh.bh_desk_level_4_rpl_code,
          ssbh.bh_desk_level_5_id,
          ssbh.bh_desk_level_5_name,
          ssbh.bh_desk_level_5_rpl_code,
          ssbh.bh_portfolio_id,
          ssbh.bh_portfolio_name,
          ssbh.bh_portfolio_rpl_code
     FROM SOURCE_SYSTEM ss, source_system_bh ssbh
     WHERE ss.SOURCE_SYSTEM_ID = ssbh.SOURCE_SYSTEM_ID
   UNION ALL
   SELECT a.METRIC_ID,
          ss.SOURCE_SYSTEM_ID,
          ss.REGION_ID,
          NVL (a.AGE_HADOOP_LASTLOAD, SYSDATE - 2) last_load,
          NVL (a.AGE_HADOOP_NEXTLOAD, SYSDATE - 1) next_load,
          DECODE (
             a.AGE_HADOOP_NEXTLOAD,
             NULL, SYSDATE,

             a.AGE_HADOOP_NEXTLOAD
             + DECODE (TO_CHAR (a.AGE_HADOOP_NEXTLOAD + 1, 'd'),
                       6, 3,
                       7, 2,
                       1))
             after_next_load,
          ss.BH_BUSINESS,
          ss.BH_SUB_BUSINESS,
          ss.BH_TRADING_UNIT,
          ss.SYSTEM_FOLDER,
          ss.REGION_FOLDER,
          ss.SYSTEM_FOLDER_AUX,
          ss.NUM_REDUCE_TASK,
          ss.MAPRED_CHILD_JAVA_OPTS,
          ss.IO_SORT_MB,
          ss.cftrFile,
          SOURCE_SYSTEM_CRDS_NAME,
          ssbh.bh_volcker_trading_desk,
          ssbh.bh_volcker_trading_desk_full,
          ssbh.bh_lowest_level_rpl_code,
          ssbh.bh_lowest_level_rpl_full_name,
          ssbh.bh_lowest_level_rpl,
          ssbh.bh_charge_report_unit_code,
          ssbh.bh_charge_report_unit,
          ssbh.bh_charge_report_parent_code,
          ssbh.bh_charge_report_parent,
          ssbh.bh_ubr_level_1_id,
          ssbh.bh_ubr_level_1_name,
          ssbh.bh_ubr_level_1_rpl_code,
          ssbh.bh_ubr_level_2_id,
          ssbh.bh_ubr_level_2_name,
          ssbh.bh_ubr_level_2_rpl_code,
          ssbh.bh_ubr_level_3_id,
          ssbh.bh_ubr_level_3_name,
          ssbh.bh_ubr_level_3_rpl_code,
          ssbh.bh_ubr_level_4_id,
          ssbh.bh_ubr_level_4_name,
          ssbh.bh_ubr_level_4_rpl_code,
          ssbh.bh_ubr_level_5_id,
          ssbh.bh_ubr_level_5_name,
          ssbh.bh_ubr_level_5_rpl_code,
          ssbh.bh_ubr_level_6_id,
          ssbh.bh_ubr_level_6_name,
          ssbh.bh_ubr_level_6_rpl_code,
          ssbh.bh_ubr_level_7_id,
          ssbh.bh_ubr_level_7_name,
          ssbh.bh_ubr_level_7_rpl_code,
          ssbh.bh_ubr_level_8_id,
          ssbh.bh_ubr_level_8_name,
          ssbh.bh_ubr_level_8_rpl_code,
          ssbh.bh_ubr_level_9_id,
          ssbh.bh_ubr_level_9_name,
          ssbh.bh_ubr_level_9_rpl_code,
          ssbh.bh_ubr_level_10_id,
          ssbh.bh_ubr_level_10_name,

          ssbh.bh_ubr_level_10_rpl_code,
          ssbh.bh_ubr_level_11_id,
          ssbh.bh_ubr_level_11_name,
          ssbh.bh_ubr_level_11_rpl_code,
          ssbh.bh_ubr_level_12_id,
          ssbh.bh_ubr_level_12_name,
          ssbh.bh_ubr_level_12_rpl_code,
          ssbh.bh_ubr_level_13_id,
          ssbh.bh_ubr_level_13_name,
          ssbh.bh_ubr_level_13_rpl_code,
          ssbh.bh_ubr_level_14_id,
          ssbh.bh_ubr_level_14_name,
          ssbh.bh_ubr_level_14_rpl_code,
          ssbh.bh_desk_level_1_id,
          ssbh.bh_desk_level_1_name,
          ssbh.bh_desk_level_1_rpl_code,
          ssbh.bh_desk_level_2_id,
          ssbh.bh_desk_level_2_name,
          ssbh.bh_desk_level_2_rpl_code,
          ssbh.bh_desk_level_3_id,
          ssbh.bh_desk_level_3_name,
          ssbh.bh_desk_level_3_rpl_code,
          ssbh.bh_desk_level_4_id,
          ssbh.bh_desk_level_4_name,
          ssbh.bh_desk_level_4_rpl_code,
          ssbh.bh_desk_level_5_id,
          ssbh.bh_desk_level_5_name,
          ssbh.bh_desk_level_5_rpl_code,
          ssbh.bh_portfolio_id,
          ssbh.bh_portfolio_name,
          ssbh.bh_portfolio_rpl_code
     FROM SOURCE_SYSTEM_METRIC a, SOURCE_SYSTEM ss,
SOURCE_SYSTEM_BH ssbh
    WHERE a.SOURCE_SYSTEM_ID = ss.SOURCE_SYSTEM_ID and ss.SOURCE_SYSTEM_ID = ssbh.SOURCE_SYSTEM_ID;
