--liquibase formatted sql
--changeset ${vr_owner_user}_CODE:VIEW_VW_VRI_DESK_MAPPING runOnChange:TRUE  failOnError:TRUE splitStatements:TRUE


  CREATE OR REPLACE FORCE VIEW "VW_VRI_DESK_MAPPING" ("ID", "DESK_ID", "DESK_NAME", "AGENCY_ID", "DESK_DESCRIPTION", "ASOFDATE", "METRICS_MEETING", "REGION", "COUNTRY", "PVF_REGION", "PVF", "BSG", "DESK_OWNER") AS 
  SELECT ID, DESK_ID, DESK_NAME, AGENCY_ID, DESK_DESCRIPTION, ASOFDATE, METRICS_MEETING, REGION, COUNTRY, PVF_REGION, PVF, BSG, DESK_OWNER
FROM VRI_DESK_MAPPING D WHERE D.ASOFDATE = (SELECT MAX(D1.ASOFDATE) FROM VRI_DESK_MAPPING D1
where D1.asofdate <= (select max(S.end_date) from vw_vri_setup S));
