--liquibase formatted sql
--changeset ${vr_owner_user}_CODE:VIEW_VW_VRI_SENTIVITY_ATT_MAPPING runOnChange:TRUE  failOnError:TRUE splitStatements:TRUE


CREATE OR REPLACE FORCE VIEW VW_VRI_SENTIVITY_ATT_MAPPING ("ID", "ASOFDATE", "SENTIVITY", "RISK_FATOR_SENSITIVITY_NAME", "RISK_FACTOR_CHANGE", "RISK_FACTOR_CHANGE_UNITS", "RISK_CLASS_METHOD", "MEASUREMENT_UNIT","CATEGORY_ID","CATEGORY_NAME") AS 
  SELECT ATM.ID,
    ATM.ASOFDATE,
    ATM.SENTIVITY,
    ATM.RISK_FATOR_SENSITIVITY_NAME,
    ATM.RISK_FACTOR_CHANGE,
    ATM.RISK_FACTOR_CHANGE_UNITS,
    ATM.RISK_CLASS_METHOD,
    ATM.MEASUREMENT_UNIT,
	ATM.CATEGORY_ID,
	ATM.CATEGORY_NAME
  FROM VRI_SENSITIVITY_ATT_MAPPING ATM
  WHERE ATM.ASOFDATE =
    (SELECT MAX(ATM2.ASOFDATE)
    FROM VRI_SENSITIVITY_ATT_MAPPING ATM2
    WHERE ATM2.ASOFDATE <=
      (SELECT VRI_EXEC_DATES.NEXT_EXEC_DATE
      FROM VRI_EXEC_DATES
      WHERE VRI_EXEC_DATES.METRIC_ID = 'MRM'
      AND VRI_EXEC_DATES.COMPONENT   = 'VRI'
      )
    );
