--liquibase formatted sql
--changeset ${vr_owner_user}_CODE:VIEW_VW_VRI_SETUP runOnChange:TRUE  failOnError:TRUE splitStatements:TRUE


  CREATE OR REPLACE FORCE VIEW "VW_VRI_SETUP" ("ID", "VERSION_ID", "SUBVERSION_ID", "INITIAL_DATE", "END_DATE", "NETTING_ITR", "NETTING_IA", "NETTING_CFTR", "CALENDAR", "NA_ENRICHER", "DAT", "EXCEPTION_REPORT", "PDF", "EXCEL", "EXCEL_DAT", "SCOPE", "STATUS", "MRM_OVERRIDE", "MRM_VAL4") AS 
  SELECT ID,VERSION_ID,SUBVERSION_ID,INITIAL_DATE,END_DATE,NETTING_ITR,NETTING_IA,NETTING_CFTR,CALENDAR,NA_ENRICHER,DAT,EXCEPTION_REPORT,PDF,EXCEL,EXCEL_DAT,SCOPE,STATUS,MRM_OVERRIDE,MRM_VAL4
FROM VRI_SETUP
WHERE VRI_SETUP.STATUS = 'IN PROGRESS';
