--liquibase formatted sql
--changeset ${vr_owner_user}_CODE:VIEW_VW_VRI_D_SENSITIVITY_MAPPING runOnChange:TRUE  failOnError:TRUE splitStatements:TRUE


CREATE OR REPLACE FORCE VIEW VW_VRI_D_SENSITIVITY_MAPPING("ID", "ASOFDATE", "DESK_CODE", "SENSITIVITY_ID", "LIMIT","PRIME_FLAG") AS 
  SELECT SM.ID,
SM.ASOFDATE,
SM.DESK_CODE,
SM.SENSITIVITY_ID,
SM.LIMIT,
SM.PRIME_FLAG
FROM VRI_DESK_SENSITIVITY_MAPPING SM
WHERE SM.ASOFDATE =
(SELECT MAX(SM2.ASOFDATE) FROM VRI_DESK_SENSITIVITY_MAPPING SM2 where SM2.ASOFDATE <= (select NEXT_EXEC_DATE FROM VRI_EXEC_DATES where metric_id='MRM' and component='VRI'));