--liquibase formatted sql
--changeset ${vr_owner_user}_CODE:VIEW_VW_VRI_A_ALLOCATION_MAPPING runOnChange:TRUE  failOnError:TRUE splitStatements:TRUE


CREATE OR REPLACE FORCE VIEW VW_VRI_A_ALLOCATION_MAPPING("ID", "ASOFDATE", "ASSET_ALLOCATION", "MAPPING_VALUE", "MEASUREMENT_UNIT") AS 
  SELECT AM.ID, AM.ASOFDATE, AM.ASSET_ALLOCATION, AM.MAPPING_VALUE, AM.MEASUREMENT_UNIT
  FROM VRI_ASSET_ALLOCATION_MAPPING AM
  WHERE AM.ASOFDATE = (SELECT MAX(AM2.ASOFDATE) FROM VRI_ASSET_ALLOCATION_MAPPING AM2 WHERE AM2.ASOFDATE <= 
   (SELECT VRI_EXEC_DATES.NEXT_EXEC_DATE
    FROM VRI_EXEC_DATES
    WHERE VRI_EXEC_DATES.METRIC_ID = 'MRM' AND VRI_EXEC_DATES.COMPONENT   = 'VRI')
  );