--liquibase formatted sql
--changeset ${vr_owner_user}_CODE:PACKAGE_PKG_PROH_PROCESS runOnChange:TRUE  failOnError:TRUE splitStatements:FALSE


  CREATE OR REPLACE PACKAGE "PKG_PROH_PROCESS" AS  
  PROCEDURE P_SPLIT_CSV_PROCESS (idUpload IN NUMBER);
  FUNCTION F_CONVERT_ROWS(p_list IN CLOB) RETURN bh_clob_type PIPELINED;
  FUNCTION F_CONVERT_ROW(p_list IN VARCHAR2, token IN VARCHAR2) RETURN bh_varchar_type PIPELINED;
  FUNCTION F_FORMAT_COLUMN_CSV(field IN VARCHAR) RETURN  VARCHAR2;
  PROCEDURE P_ACCEPT_UPLOAD (IDUPLOAD IN NUMBER, IDUSER IN VARCHAR, COMMENTS IN VARCHAR);
  PROCEDURE P_REJECT_UPLOAD (P_IDUPLOAD IN NUMBER, P_IDUSER IN VARCHAR, P_COMMENTS IN VARCHAR);
  TYPE csv_table_array IS VARRAY (19) OF VARCHAR2 (4000);
  TYPE csv_table_type IS TABLE OF csv_table_array;  
  FUNCTION F_IS_EMPTY_RECORD (p_excel_record IN csv_table_array, p_total_columns IN NUMBER) RETURN BOOLEAN;
  FUNCTION F_PROH_LOAD_FILE_IN_PROH_CP(P_UPLOAD_ID IN NUMBER) RETURN BOOLEAN;
  FUNCTION F_IS_DATE(FIELD_DATE_VALUE IN VARCHAR2) RETURN DATE;
  FUNCTION F_PROH_INTERMEDIARY_TO_PROH_CP(P_ID NUMBER , p_upload_data  REF_DATA_UI_UPLOAD%ROWTYPE) RETURN BOOLEAN;
  FUNCTION F_GET_VALIDATION_MSG(code IN NUMBER)  RETURN VARCHAR2;
END PKG_PROH_PROCESS;
