--liquibase formatted sql
--changeset ${vr_owner_user}_CODE:PACKAGE_PKG_COMMON_UTILS runOnChange:TRUE  failOnError:TRUE splitStatements:FALSE


  CREATE OR REPLACE PACKAGE "PKG_COMMON_UTILS" AS 

  FUNCTION F_CONVERT_ROWS(p_list IN CLOB) RETURN clob_type PIPELINED;
  FUNCTION F_CONVERT_ROW(p_list IN VARCHAR2, token IN VARCHAR2) RETURN varchar_type PIPELINED;
  FUNCTION F_IS_DATE_OK(p_date VARCHAR2, p_format VARCHAR2) RETURN CHAR;
  FUNCTION F_FORMAT_COLUMN_CSV(field IN VARCHAR) RETURN  VARCHAR2;
  FUNCTION F_GET_VALIDATION_MSG(code IN NUMBER, field IN VARCHAR2,	ref_table IN VARCHAR2) RETURN VARCHAR2;
  FUNCTION F_IS_NUMBER (p_string IN VARCHAR2) RETURN INT;  
  FUNCTION F_CHECK_DATE_FORMAT(p_checkdate IN VARCHAR2) RETURN VARCHAR2;
  PROCEDURE P_IS_MANDATORY_NULL (field_name IN VARCHAR2,field IN OUT VARCHAR2, cont_error IN OUT NUMBER, validation_msg IN OUT VARCHAR2, ref_table IN VARCHAR2);
  PROCEDURE P_IS_MANDATORY_BLANK (field_name IN VARCHAR2,field IN OUT VARCHAR2, cont_error IN OUT NUMBER, validation_msg IN OUT VARCHAR2, ref_table IN VARCHAR2);
  PROCEDURE P_CHECK_FORMAT_FIELD(field_name IN VARCHAR2, field_value IN OUT VARCHAR2, C_SIZE_PARAM IN NUMBER, cont_error IN OUT VARCHAR2, validation_msg IN OUT VARCHAR2); 
  
END PKG_COMMON_UTILS;
