--liquibase formatted sql
--changeset ${vr_owner_user}_CODE:PACKAGE_PKG_BH_PROCESS runOnChange:TRUE  failOnError:TRUE splitStatements:FALSE


  CREATE OR REPLACE PACKAGE "PKG_BH_PROCESS" AS  
  TYPE csv_table_array IS VARRAY (18) OF VARCHAR2 (4000);
  TYPE csv_table_type IS TABLE OF csv_table_array;  
  
  PROCEDURE P_BH_INITIAL_LOADING;
  FUNCTION F_BH_LOAD_FILE_IN_STAGING(P_UPLOAD_ID IN NUMBER) RETURN BOOLEAN;
  
  PROCEDURE P_BH_UI_UPDATE_CSV(P_UI_UPLOAD IN NUMBER);
  
  PROCEDURE P_BH_GET_CONFLICT_DATA(p_conflict_id IN NUMBER, p_result OUT SYS_REFCURSOR);
  
  PROCEDURE P_GET_BH_WORKFLOW(P_WORKFLOW_TYPE_ID IN VARCHAR2,P_CONFLICTS_CSV OUT CLOB);
  PROCEDURE P_SPLIT_CSV_PROCESS (idUpload IN NUMBER);
  FUNCTION F_CONVERT_ROWS(p_list IN CLOB) RETURN bh_clob_type PIPELINED;
  FUNCTION F_CONVERT_ROW(p_list IN VARCHAR2, token IN VARCHAR2) RETURN bh_varchar_type PIPELINED;
  FUNCTION F_FORMAT_COLUMN_CSV(field IN VARCHAR) RETURN  VARCHAR2;
  PROCEDURE P_ACCEPT_UPLOAD (IDUPLOAD IN NUMBER, IDUSER IN VARCHAR, COMMENTS IN VARCHAR);
  PROCEDURE P_REJECT_UPLOAD (P_IDUPLOAD IN NUMBER, P_IDUSER IN VARCHAR, P_COMMENTS IN VARCHAR);  
  PROCEDURE P_BH_RESOLVE_CONFLICT(p_conflict_id IN NUMBER, p_selected_choice IN VARCHAR2, p_user_name IN VARCHAR2, p_comments IN VARCHAR2);
  FUNCTION F_IS_EMPTY_RECORD (p_excel_record IN csv_table_array, p_total_columns IN NUMBER) RETURN BOOLEAN;
  FUNCTION P_PROCESS_ETL_STATUS(p_upload_id IN INTEGER, p_operation_type IN INTEGER) RETURN BOOLEAN;
  PROCEDURE P_UPDATE_UPLOAD_ID_WITH_ETL(p_upload_id IN INTEGER, p_status_id IN INTEGER, p_error_return_code IN INTEGER);
END PKG_BH_PROCESS;
