--liquibase formatted sql
--changeset ${vr_owner_user}_CODE:PACKAGE_BODY_PKG_REGIONS runOnChange:TRUE  failOnError:TRUE splitStatements:FALSE stripComments:FALSE


  CREATE OR REPLACE PACKAGE BODY "PKG_REGIONS" 
AS
   FUNCTION F_SET_ROLL_DATE(P_REGION source_system.region_id%TYPE)
    RETURN NUMBER
  IS
  BEGIN
    UPDATE REGIONS RG
    SET RG.PREPREV_DATE = RG.PREV_DATE,
      RG.PREV_DATE      = RG.COB_DATE,
      RG.COB_DATE       = RG.NEXT_DATE,
      RG.NEXT_DATE      = RG.NEXT_DATE + DECODE(1 + TRUNC (RG.NEXT_DATE+1) - TRUNC (RG.NEXT_DATE+1, 'IW'), 6, 3, 7, 2, 1)
    WHERE RG.REGION_ID=P_REGION;
    
    IF SQL%ROWCOUNT = 1 THEN
      COMMIT;
      RETURN 0;
    ELSE
      ROLLBACK;
      RETURN 1;
    END IF;
    
  END F_SET_ROLL_DATE;
  FUNCTION F_GET_COB_DATE(
      P_REGION IN VARCHAR2,
      P_COB_DATE OUT DATE)
    RETURN NUMBER
  IS
  BEGIN
    SELECT MAX(COB_DATE)
    INTO P_COB_DATE
    FROM REGIONS RG
    WHERE RG.REGION_ID=P_REGION;
    RETURN 0;
  EXCEPTION
  WHEN OTHERS THEN
    RETURN 1;
  END F_GET_COB_DATE;
  FUNCTION F_GET_PREV_DATE(
      P_REGION IN VARCHAR2,
      P_PREV_DATE OUT DATE)
    RETURN NUMBER
  IS
  BEGIN
    SELECT MAX(PREV_DATE)
    INTO P_PREV_DATE
    FROM REGIONS RG
    WHERE RG.REGION_ID=P_REGION;
    RETURN 0;
  EXCEPTION
  WHEN OTHERS THEN
    RETURN 1;
  END F_GET_PREV_DATE;
  FUNCTION F_GET_NEXT_DATE(
      P_REGION IN VARCHAR2,
      P_NEXT_DATE OUT DATE)
    RETURN NUMBER
  IS
  BEGIN
    SELECT MAX(NEXT_DATE)
    INTO P_NEXT_DATE
    FROM REGIONS RG
    WHERE RG.REGION_ID=P_REGION;
    RETURN 0;
  EXCEPTION
  WHEN OTHERS THEN
    RETURN 1;
  END F_GET_NEXT_DATE;
END PKG_REGIONS;
