  --liquibase formatted sql
--changeset P17.05.30:GBSVR-34612
CREATE TABLE DUMMY_TABLE 
(
  COLUMN1 NUMBER NOT NULL 
, COLUMN2 VARCHAR2(20) 
, COLUMN3 VARCHAR2(20) 
);
--rollback DROP TABLE
--rollback DUMMY_TABLE;

--changeset P17.05.30:GBSVR-34612-2 failOnError:FALSE
CREATE INDEX DUMMY_TABLE_INDEX1 ON DUMMY_TABLE (COLUMN1 ASC);
-- DROP INDEX DUMMY_TABLE_INDEX1 --rollback;

--changeset P17.05.30:GBSVR-34612-2 failOnError:FALSE --Do not validate
ALTER TABLE DUMMY_TABLE
ADD CONSTRAINT DUMMY_TABLE_PK PRIMARY KEY 
(
  COLUMN1 
)
USING INDEX DUMMY_TABLE_INDEX1
ENABLE;
--rollback  ALTER TABLE DUMMY_TABLE
--rollback DROP CONSTRAINT "DUMMY_TABLE_PK";
set define off;
