--liquibase formatted sql
--changeset ${vr_owner_user}_CODE:TYPE_SDATA_AUDIT_HISTORY_DATA_TYPE runOnChange:TRUE  failOnError:TRUE splitStatements:FALSE


  CREATE OR REPLACE TYPE "SDATA_AUDIT_HISTORY_DATA_TYPE" AS OBJECT
(AUDIT_KEY VARCHAR2 (100),
 AUDIT_VALUE VARCHAR2 (500),
 MODIFIED_FROM_VALUE VARCHAR2 (500 BYTE));
